### ISSUE TITLE
NBA2K Tournament and drafts

### ISSUE THREAD

**Issue by theloup1982** [yo1995/nba2k-shotchart-project#6]
Hello,

I came across some of your work on NBA2k. A few of my friends have been doing some drafts and simulated playoff tournaments. It has been a lot fun. Looking to connect with good resources and developers to modify the game a bit that will enhance the drafting and simulation experience. Wanted to see if you had an interest in playing around with a few items on it.

**Comment by yo1995** [comment]
Hi, thanks for reaching out! 🙂 I'm willing to learn about the details.

As for this project, since I only play 2K11 occasionally, and don't have any newer versions of the game, I might not be able to create a tool for the latest 2K games (newer versions might have different data structures, memory layout, anti-cheating protection, etc.).

Also, this tool only applies to an in-game, play by play gameplay. It relies on the in-game generated data to draw the shotchart. If you just simulate through a season without getting into the game in real time, shot-by-shot data cannot be obtained. 😕 

Please let me know how I can help.

**Comment by theloup1982** [comment]
Thanks for the quick reply. Let me know best email to reach you on and I can send over a couple of things I am looking at doing and we can have a chat. You can email me at wolfe.jordan@gmail.com and I will respond. 

Thanks,

Jordan

**Comment by theloup1982** [comment]
Just a bit more info. I currently run virtual simulated tournaments for NBA 2K20with friends where we do a fantasy draft and then have the tournaments simulated with players dating back to the 1950s. The goal is to build a platform that will allow for these fantasy simulated league and tournament play for a variety of sports games. It is fantasy sports meets the virtual world and a way to keep in touch with friends.

There are a few items I would like to start with that includes getting a script built to allow games to continuously run. We currently run simulated playoff tournaments and we have to manually start each new game instead of letting the machine run game after game. 

More than happy to share more with you and see if you are interested in it.

Thanks,

Jordan

**Comment by yo1995** [comment]
Close due to inactivity.
